version: "3.7"

services:

  postgres:
    image: wodby/postgres:$POSTGRES_TAG
    container_name: "${PROJECT_NAME}_postgres"
    stop_grace_period: 30s
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    volumes:
    - ./postgres-init:/docker-entrypoint-initdb.d # Place init file(s) here.
    - /path/to/postgres/data/on/host:/var/lib/postgresql/data # Use bind mount
    ports:
      - "5433:5432"

